### ISSUE TITLE
Add mouse up/down events to Button

### ISSUE THREAD

**Issue by enzinia** [caddijp/frontend#181]
Need more events to fix onClick timing problem.

Related: 
* https://github.com/caddijp/herodotus-ui/issues/324
* https://github.com/caddijp/herodotus-ui/issues/334

**Comment by 9renpoto** [comment]
fixed it :)

- https://github.com/caddijp/frontend/pull/147
- https://github.com/caddijp/frontend/releases/tag/v0.1.0

thank you remind!
